### ISSUE TITLE
AttributeError: 'Asset' object has no attribute 'properties'

### ISSUE THREAD

**Issue by rsignell** [stac-extensions/xarray-assets#6]
When I try to run the [python example in the readme](https://github.com/stac-extensions/xarray-assets?tab=readme-ov-file#python-example), I get an error about properties.   Guessing something changed with pystac?

![image](https://github.com/user-attachments/assets/f4de0638-b8a9-4993-a981-8e8bb7a7fe5e)

**Comment by TomAugspurger** [comment]
https://github.com/stac-extensions/xarray-assets/issues/7 should fix this. I guess the right attribute is `.extra_fields`, not `.properties`.
